/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makecoffee;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author M7md Qash
 */
public class MakeCoffeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form MakeCoffeeFrame
     */
    CoffeeMachine cm;

    public MakeCoffeeFrame() {
        initComponents();
        cm = new CoffeeMachine(new Beans(), new WaterTank(), new Grinder(), new Trash(), true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        AddCoffeeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PercentTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AddWaterTextField = new javax.swing.JTextField();
        StartButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        EsepresooRadioButton = new javax.swing.JRadioButton();
        AmericanRadioButton = new javax.swing.JRadioButton();
        SingleRadioButton = new javax.swing.JRadioButton();
        DoubleRadioButton = new javax.swing.JRadioButton();
        getInfoButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AddWaterButton = new javax.swing.JButton();
        GrinderTextField = new javax.swing.JTextField();
        GrinderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add Coffee:");

        AddCoffeeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCoffeeTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Percent of Arabica Coffee:");

        PercentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Add Water:");

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(EsepresooRadioButton);
        EsepresooRadioButton.setText("Esepresoo");
        EsepresooRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsepresooRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(AmericanRadioButton);
        AmericanRadioButton.setText("American");

        buttonGroup1.add(SingleRadioButton);
        SingleRadioButton.setText("Single");

        buttonGroup1.add(DoubleRadioButton);
        DoubleRadioButton.setText("Double");

        getInfoButton.setText("GetInfo");
        getInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getInfoButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Grinder:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Menu");
        jLabel5.setToolTipText("");

        jLabel6.setText("Choose Coffee");

        jLabel7.setText("Choose Type");

        AddButton.setText("Add Coffee");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        AddWaterButton.setText("Add Water");
        AddWaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWaterButtonActionPerformed(evt);
            }
        });

        GrinderButton.setText("Grinder your Coffee");
        GrinderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrinderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(StartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EsepresooRadioButton)
                            .addComponent(AmericanRadioButton))
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DoubleRadioButton)
                            .addComponent(SingleRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ClearButton)
                        .addGap(82, 82, 82)
                        .addComponent(getInfoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GrinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(GrinderButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(171, 171, 171)
                                        .addComponent(jLabel7)))))
                        .addGap(201, 204, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddWaterTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PercentTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddCoffeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddButton)
                            .addComponent(AddWaterButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ClearButton, StartButton, getInfoButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddButton, AddWaterButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PercentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddCoffeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(AddWaterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddWaterButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EsepresooRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SingleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AmericanRadioButton)
                    .addComponent(DoubleRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GrinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrinderButton))
                .addGap(23, 23, 23)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartButton)
                    .addComponent(ClearButton)
                    .addComponent(getInfoButton))
                .addGap(113, 113, 113))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddButton, AddCoffeeTextField, AddWaterTextField, PercentTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCoffeeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCoffeeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCoffeeTextFieldActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here: 

        cm.clear();
        JOptionPane.showMessageDialog(this, "Trash was clear");
        try {
            FileWriter writer = new FileWriter("tracing.txt", true);
            writer.write("\nThe Machine was Clear");

            writer.close();

        } catch (IOException ex) {
            Logger.getLogger(MakeCoffeeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ClearButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:

        try {
            if (!cm.check()) {
                JOptionPane.showMessageDialog(this, "the machine are not ready ");
            } else {

                cm.shotDose(EsepresooRadioButton.isSelected(), SingleRadioButton.isSelected(), AmericanRadioButton.isSelected(), DoubleRadioButton.isSelected());

                if (EsepresooRadioButton.isSelected() == false && AmericanRadioButton.isSelected() == false) {
                    JOptionPane.showMessageDialog(this, "You Should Choice The Coffee Type!");
                } else if (SingleRadioButton.isSelected() == false && DoubleRadioButton.isSelected() == false) {
                    JOptionPane.showMessageDialog(this, "You Should Choice Single or Double!");
                } else if (EsepresooRadioButton.isSelected() || AmericanRadioButton.isSelected() && SingleRadioButton.isSelected() || DoubleRadioButton.isSelected()) {
                    try {
                        JOptionPane.showMessageDialog(this, "your coffee are ready\nthe grinder is " + cm.grindlevel() + "\nthe caffiene  is :" + cm.caffiene(EsepresooRadioButton.isSelected(), SingleRadioButton.isSelected(), AmericanRadioButton.isSelected(), DoubleRadioButton.isSelected()));
                    } catch (GrinderException ex) {
                        Logger.getLogger(MakeCoffeeFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try {
                    FileWriter writer = new FileWriter("tracing.txt", true);
                   

                        writer.write("\nA cup of coffee was made");
                        if (EsepresooRadioButton.isSelected() && SingleRadioButton.isSelected()) {
                            writer.write(cm.Espresosingle());
                        } else if (EsepresooRadioButton.isSelected() && DoubleRadioButton.isSelected()) {
                            writer.write(cm.Espresodouble());
                        } else if (AmericanRadioButton.isSelected() && SingleRadioButton.isSelected()) {
                            writer.write(cm.americansingle());
                        } else if (AmericanRadioButton.isSelected() && DoubleRadioButton.isSelected()) {
                            writer.write(cm.americandouble());
                        }

                        writer.close();
                    

                } catch (IOException ex) {
                    Logger.getLogger(MakeCoffeeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        } catch (BeansException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (WaterTankException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (TrashException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

      

    }//GEN-LAST:event_StartButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        double Percent = Double.parseDouble(PercentTextField.getText());
        double Coffee = Double.parseDouble(AddCoffeeTextField.getText());

        try {
            cm.fillBeans(Coffee, Percent);
        } catch (BeansException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        try {
            FileWriter writer = new FileWriter("tracing.txt", true);
            writer.write("\nCoffee was added to the machine in the amount of " + Coffee);

            writer.close();

        } catch (IOException ex) {
            Logger.getLogger(MakeCoffeeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        AddCoffeeTextField.setText("");
        PercentTextField.setText("");

    }//GEN-LAST:event_AddButtonActionPerformed

    private void PercentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PercentTextFieldActionPerformed

    private void getInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getInfoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(cm.getInfo());
    }//GEN-LAST:event_getInfoButtonActionPerformed

    private void EsepresooRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsepresooRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsepresooRadioButtonActionPerformed

    private void AddWaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWaterButtonActionPerformed
        // TODO add your handling code here:
        double Water = Double.parseDouble(AddWaterTextField.getText());
        try {
            cm.fillWater(Water);
        } catch (WaterTankException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        try {
            FileWriter writer = new FileWriter("tracing.txt", true);
            writer.write("\nWater was added to the machine in the amount of " + Water);

            writer.close();

        } catch (IOException ex) {
            Logger.getLogger(MakeCoffeeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        AddWaterTextField.setText("");
    }//GEN-LAST:event_AddWaterButtonActionPerformed

    private void GrinderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrinderButtonActionPerformed
        // TODO add your handling code here:
        int grinder = Integer.parseInt(GrinderTextField.getText());
        try {
            cm.grinding(grinder);
        } catch (GrinderException ex) {
            Logger.getLogger(MakeCoffeeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        GrinderTextField.setText("");
    }//GEN-LAST:event_GrinderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeCoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeCoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeCoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeCoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeCoffeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AddCoffeeTextField;
    private javax.swing.JButton AddWaterButton;
    private javax.swing.JTextField AddWaterTextField;
    private javax.swing.JRadioButton AmericanRadioButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JRadioButton DoubleRadioButton;
    private javax.swing.JRadioButton EsepresooRadioButton;
    private javax.swing.JButton GrinderButton;
    private javax.swing.JTextField GrinderTextField;
    private javax.swing.JTextField PercentTextField;
    private javax.swing.JRadioButton SingleRadioButton;
    private javax.swing.JButton StartButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton getInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
